apiVersion: apps/v1
kind: Deployment
metadata:
  # Dit wordt later overschreven door de Kustomization naar de 'mealie' namespace
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie # Cruciaal: dit moet 'mealie' zijn zodat de Service de Pod vindt.
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v3.2.1 # De specifieke image die u wenst
          name: mealie
          ports:
            - containerPort: 9000 # Correcte poort voor Mealie V3
          env:
          # Omgevingsvariabelen behouden van eerdere concepten
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          
          # Cruciaal: De volume mounts om de data op te slaan
          volumeMounts:
          - name: data
            mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-pvc # Zorgt voor persistente opslag van recepten
