# Bestandsnaam: apps/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Bundelt de applicaties
  - linkding
  - mealie
  # Bundelt de gedeelde netwerkinfrastructuur (de tunnel)
  - ../networking/cloudflare-tunnel
